### ISSUE TITLE
Can I use this for commercial purpose?

### ISSUE THREAD

**Issue by kamlekar** [timoh6/timoh6.github.com#1]
Hi. I really admire your work. I have a similar requirement for commercial work in my company. Since, you haven't mentioned the license I am asking here whether can I go ahead or not?

Expecting positive response from you :)

Thanks.

**Comment by timoh6** [comment]
(Just out of interest) I suppose you mean the small JS quiz app? Anyway, go ahead.

**Comment by kamlekar** [comment]
Yes I meant this 

http://timoh6.github.io/WebAppSecQuiz/

Thanks :)
